# Generated by Django 5.2.4 on 2025-08-08 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electircal', '0002_category_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default=1, upload_to='Blog/'),
            preserve_default=False,
        ),
    ]
