# Generated by Django 5.2.5 on 2025-08-08 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electircal', '0003_blog_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250)),
                ('job', models.TextField()),
            ],
        ),
    ]
