# Generated by Django 5.2.5 on 2025-08-08 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electircal', '0004_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='team_images/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='job',
            field=models.CharField(max_length=100),
        ),
    ]
